spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: canal
    password: canal
    publisher-confirm-type: correlated #消息确认配置项，确认消息已发送到交换机(Exchange)
    publisher-returns: true # 确认消息已发送到队列(Queue)